directories:
  output: release
  buildResources: build
appId: io.github.alibaba.lightproxy
asar: true
mac:
  category: ''
win:
  target: nsis
  icon: ./static/icon.png
files:
  - filter:
      - dist/*.js
      - dist/*.html
      - dist/devtools-frontend/**/*
      - dist/files/*.png
      - dist/files/node/modules
      - dist/files/proxy_conf_helper
      - package.json
      - main.js
electronVersion: 8.2.3
