directories:
  output: release
  buildResources: build
appId: org.lightproxy
asar: true
mac:
  category: ''
  icon: ./vendor/files/icon.icns
win:
  target: nsis
  icon: ./vendor/files/icon.png
files:
  - filter:
      - dist/*.js
      - dist/*.html
      - dist/files/*.png
      - dist/files/node/modules
      - dist/files/proxy_conf_helper
      - package.json
      - main.js
electronVersion: 8.0.0
